services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  System25\T3sports\:
    resource: '../Classes/*'
    exclude: 
      - '../Classes/Model/*'
      # FIXME: exclude Decorator for now
      - '../Classes/Decorator/*'

  System25\T3sports\Filter\MatchFilter:
    public: true
  System25\T3sports\Twig\Extension\DataProvider:
    public: true
